### PR TITLE
Accessibility update color contrast

### PR DESCRIPTION
**Pull request by Arhell**

### CODE REVIEW

**Review by ADmad — APPROVED** [review]

**Comment by ADmad** [comment]
@Arhell Can you please show before/after screenshot for others to review.

**Comment by othercorey** [comment]
@yeliparra fyi, we are fixing the design

**Comment by ADmad** [comment]
To provide more context this change is based on a comment made by a user that some texts were very light on white background and are not good for accessibility.

**Comment by Arhell** [comment]
check contrast here https://webaim.org/resources/contrastchecker/

**Pull request merged**
