### PR TITLE
Accessibility fix duplicate ids

### PR DESCRIPTION
**Pull request by Arhell**

### CODE REVIEW

**Comment by ndm2** [comment]
This kinda breaks it even more, doesn't it, leaving `aria-labelledby` pointing to nothing? I'd suggest to make the ID unique instead, for example using `$key` as a suffix.

**Comment by Arhell** [comment]
@ndm2 Please look, did I do it right?

**Comment by ndm2** [comment]
The result should be fine, but it's a somewhat unusual way to concatenate strings :) I'd rather do it like

```php
attribute="gridSystemModalLabel-<?= $key ?>"
```

**Comment by Arhell** [comment]
> 

Done thanks

**Comment by Arhell** [comment]
> The result should be fine, but it's a somewhat unusual way to concatenate strings :) I'd rather do it like
> 
> ```
> attribute="gridSystemModalLabel-<?= $key ?>"
> ```

Done thanks

**Review by ndm2 — APPROVED** [review]

**Pull request merged**
