### PR TITLE
Add PingPing.io

### PR DESCRIPTION
**Pull request by cleptric**
Stefan of pingping.io was so kind, to give CakePHP a free enterprise plan for monitoring all our apps and SSL certificates. He kindly asked to include his logo on our page.

### CODE REVIEW

**Comment by markstory** [comment]
How does this end up displaying?

**Comment by cleptric** [comment]
Screenshot 2019-06-11 at 19 21 38

**Comment by markstory** [comment]
Could we make pingping the same width as the rackspace logo?

**Comment by cleptric** [comment]
Yes, I'll resize it.

**Comment by cleptric** [comment]
Screenshot 2019-06-14 at 18 41 50

**Pull request merged**
