### PR TITLE
showcase printivo.com on cakephp.org

### PR DESCRIPTION
**Pull request by kheengz**
@cakedeploy added records to showcase printivo.com on cakephp.org
which also references issues [#120](https://github.com/Printivo/printivo/issues/120) on [Printivo Github](https://github.com/Printivo/printivo)

### CODE REVIEW

**Comment by yeliparra** [comment]
Merged into stage, will do some internal tests to deploy in live.

**Comment by kheengz** [comment]
@yeliparra ok thanks...looking forward to that.

**Comment by yeliparra** [comment]
@kheengz 'Printivo Test 1' is the company name? . This is how it's looking now https://www.dropbox.com/s/x3lmx9r6r75laxk/Screenshot%202017-06-30%2014.01.25.png?dl=0.

Feel free to add another commit for fixing the name if it's wrong, otherwise, let me know and I can deploy live.

**Comment by kheengz** [comment]
@yeliparra ohhhh...my bad the name is actually wrong those were test data.
can i still commit on same branch?

**Comment by yeliparra** [comment]
@kheengz  yes you can.

**Comment by kheengz** [comment]
@yeliparra awww, i already created another PR #98

**Pull request merged**
