### PR TITLE
Add more CakePHP Jobs & Developers Websites

### LINKED ISSUE #116: Add more CakePHP Jobs & Developers Websites
There is [a question in the CakePHP forum whether there is a place in the forum for posting CakePHP related freelance jobs](https://discourse.cakephp.org/t/is-there-a-place-in-forum-to-find-cakephp-related-remote-job-freelance/5099). Currently there isn't and probably there sthouldn't be, as a forum isn't very effective for such content.

There are plenty of such websites out there.

We already have a short list for finding CakePHP related jobs and/or frelancers at https://cakephp.org/get-involved#findjobdeveloper

I prepared a list or better said two lists for CakePHP jobs and CakePHP developers at https://gist.github.com/ravage84/42aa762d672efc1a3f0d9508f6d887e3 which we can replace the current list with.

### PR DESCRIPTION
**Pull request by ravage84**
Divide job/project sites and developer/freelancer sites visually, in menu and in configuration.

Replace redundant code with two foreachs, reading everything from the configuration.

Closes #116

### CODE REVIEW

**Comment by ravage84** [comment]
@Megslalk  what do you think about this?

**Comment by Megslalk** [comment]
Hey @ravage84 - do you maybe have a screenshot? Not Sure Im understanding properly! :)

**Comment by ravage84** [comment]
@Megslalk sure. Here we go:
grafik
grafik

Nonetheless, somebody more familiar with the sites' code should have a look over it, too.

**Comment by ravage84** [comment]
@Megslalk what can I do to push this forward?

**Comment by Megslalk** [comment]
@ravage84 Caught up with @phpnut - he's wanting to check in with Florian to see if cakephpjobs.com is going to get the redesign with the new branding first

**Comment by steinkel** [comment]
@phpnut ping

**Comment by steinkel** [comment]
obsolete

**Pull request closed without merging**
