### PR TITLE
Add secret & secret_verified to default user's insert query

### PR DESCRIPTION
**Pull request by yomexzo**
Migrations fails on fresh install.
It's because CakeDC/users added `secret` & `secret_verified` columns to the `users` table. [Here's the current version](https://github.com/CakeDC/users/blob/5584c2929ba84f4dba680d271a021dc835bf9cff/config/Migrations/20161031101316_AddSecretToUsers.php) of the migration file from CakeDC/users

This PR sets the two columns as `null`

### CODE REVIEW

**Comment by josegonzalez** [comment]
Is that plugin not pinned?

**Comment by josegonzalez** [comment]
Nvm I see whats going on, we should change the migration to specify the fields being inserted.

**Comment by yomexzo** [comment]
i'd do that. i believe you mean `insert into table (column list) values ....` @josegonzalez

**Comment by josegonzalez** [comment]
Yes.

**Comment by yomexzo** [comment]
Closing in favour of #96. It fixed the same thing

**Pull request closed without merging**
