### PR TITLE
CakePHP 3.6 Upgrade

### PR DESCRIPTION
**Pull request by ravage84**
While working on #117, I noticed a few issues with DebugKit. Realized it was quite outdated, so the rest of the dependencies were. Updated/upgraded some, including CakePHP itself to the newest stable.

In some cases I used shortest way possible to get it working. So I guess somebody with more familiarity of the sites code should have good look at it.

### CODE REVIEW

**Comment by yeliparra** [comment]
Merged into stage to perform QA before deploying live. 

@ravage84 `bin/cake migrations migrate` is working for you? On deploying is showing an error

`Task `Dump` not found. Maybe you made a typo or a plugin is missing or not loaded? in [/var/virtual/cakephp/stage/30102018-185624/vendor/cakephp/cakephp/src/Console/Shell.php, line 326]`

There is also an internal error on the admin part (view, edit projects).

**Comment by ravage84** [comment]
> @ravage84 `bin/cake migrations migrate` is working for you? On deploying is showing an error

Honestly, forgot to check.

**Comment by yeliparra** [comment]
@ravage84 fixed the issue with migrations and some other deprecated methods have been replaced, however, there is still some work to do with a couple of plugins that needs to be updated in the App.   See here https://gist.github.com/yeliparra/e12d09aea6fa1ddf7d21893e94de4c57

**Comment by ravage84** [comment]
@yeliparra thanks.

The deprecation warnings relating to the Burzum/Imagine plugin can't be resolved at the moment as it seems the website uses the most up to date version 2.1.1 :
https://github.com/burzum/cakephp-imagine-plugin/tags

One should probably raise an issue on that repo.

**Pull request merged**
