### PR TITLE
start fr translation

### PR DESCRIPTION
**Pull request by cake17**
Please do not merge, work in progress.

@HavokInspiration @antograssiot Just a start, if you don't know what to do during holidays.... 😄

### CODE REVIEW

**Comment by antograssiot** [comment]
@cake17 what is the plan for this translation ? I mean are you in touch with the owner of the cakephp.fr domain and is he ok to transfer it to the organisation ?

**Comment by cake17** [comment]
I'm not sure he would be ok to tranfer the ownership to the organisation but I can ask him to redirect cakephp-fr.org to cakephp.org.

Or we can consider to create a subdomain fr.cakephp.org ?

**Comment by andtxr** [comment]
I will start the pt translation soon guys. When we reach something concrete a PR to include a lang selector in the top navbar would be good. For my part, I think I'll keep the cakephp-br.org domain for independent content. I am still thinking about it.

**Comment by cake17** [comment]
@antograssiot Is it necessary to have a cakephp.fr  or cakephp-fr.org for this website ?

It is a CakePHP app, so we probably can internationalize the app with a lang selector in the top navbar that will add a query string ?lang=fr to the url, defining the language (default to english of course if no query string).

This also could show good practices  and be an example for developers who want to internationalize their app.

**Comment by ravage84** [comment]
You guys should probably talk to the Japanese guys, so both teams have the same idea of how to tackle this.

**Comment by chinpei215** [comment]
I added an environment variable - CAKE_LOCALE,  to handle locale in #39. I thought it was the most easy way to do it with less code change. But I am OK with handling locale by using query string ?lang=ja.

**Pull request merged**
