### PR TITLE
Refs #55 adding language selector to top menu. Thanks to @lorenzo.

### PR DESCRIPTION
**Pull request by pedrofs**
It solves #55 

Thanks to @lorenzo for his nice routing trick: https://github.com/steinkel/cakefest2016/blob/advanced/config/routes.php

It looks like this:
closed
cakephp_selector_01

opened
cakephp_selector_02

### CODE REVIEW

**Comment by markstory** [comment]
Not sure about the grey inside the red. Could the dropdown be red as well?

**Comment by pedrofs** [comment]
Sure, let me try that.

**Comment by pedrofs** [comment]
closed
cakephp_selector_03

opened
cakephp_selector_04

what do you think?

**Comment by pedrofs** [comment]
Or opened like this:
cakephp_selector_05

**Comment by markstory** [comment]
2nd one looks better to me.

**Pull request merged**
