### PR TITLE
CakePHP 3.6 Upgrade (continued)

### PR DESCRIPTION
**Pull request by ravage84**
Building @yeliparra 's changes in the stage branch after she took my work from #118 .

### CODE REVIEW

**Comment by ravage84** [comment]
What can I do to push this forward?

**Comment by yeliparra** [comment]
There is still a list of deprecated https://gist.github.com/yeliparra/e12d09aea6fa1ddf7d21893e94de4c57

**Comment by yeliparra** [comment]
@ravage84 I had missed this, I am doing some tests now in stage before merging into master.

**Comment by yeliparra** [comment]
@ravage84 the only deprecated now are the ones from ImagineBehavior https://gist.github.com/yeliparra/b7745257af9de3eeb03f4bec8894fc0e 

It seems burzum/cakephp-imagine-plugin needs to be upgraded to "^3.0", now it's using "~2.0". 

http://nimb.ws/QlWdH9

**Comment by ravage84** [comment]
The latest release of Burzum's ImagineBehavior plugin is 2.1.1

https://github.com/burzum/cakephp-imagine-plugin/releases/tag/2.1.1

I'm not sure there is a compatible (as in not using deprecated methods) version of that plugin... :man_shrugging:

**Comment by yeliparra** [comment]
@ravage84 what about using branch 3.x? I think that one would work.

**Comment by ADmad** [comment]
> I'm not sure there is a compatible (as in not using deprecated methods) version of that plugin...

Why not just turn off deprecation warnings reporting in app config?

**Comment by yeliparra** [comment]
that is another option, but we will have to live with those deprecates. We could do that.

**Pull request merged**
