### PR TITLE
pt_BR i18n + some code review & fix

### PR DESCRIPTION
**Pull request by andtxr**
Ready to merge. 👍 

Pages translated to pt_BR:

- [x] Home
- [x] Business solutions
- [x] Privacy policy
- [x] Community center
- [x] Get paid to write
- [x] Logos and trademarks
- [x] Team
- [x] Videos
- [x] Showcase

Other changes:

- Fixed some missing translation function in templates.
- Added missing links in community menu.
- Updated default .pot file with the latest translatable strings from config and src folders.
- Fixed wrong services list in the page Business Solutions.

More details in the commits.

### CODE REVIEW

**Comment by andtxr** [comment]
Issue #79 is fixed in this PR.

**Comment by andtxr** [comment]
One page to go. 💃

**Comment by andtxr** [comment]
Finished.

**Comment by yeliparra** [comment]
@andtxr deployed in live!.

Thank you!!

**Comment by andtxr** [comment]
YEY! Awesome!

**Pull request merged**
